### PR TITLE
Bug fix #244: Core initial guess

### LINKED ISSUE #244: Core Hamiltonian initial guess fails badly for open-shell

### PR DESCRIPTION
**Pull request by stigrj**
Fixing issue #244. Problem was not open-shell but rather that the core guess orbitals were not correctly distributed with MPI. Moved the `initial_guess::rotate_orbitals` from sad.cpp to core.cpp since the latter is more fundamental.

- [x] Ready to merge

### CODE REVIEW

File: src/initial_guess/core.cpp [hunk 1]
```diff
@@ -276,4 +256,32 @@ OrbitalVector initial_guess::core::project_ao(double prec, const Nuclei &nucs, i
     return Phi;
 }
 
+OrbitalVector initial_guess::core::rotate_orbitals(double prec, ComplexMatrix &U, OrbitalVector &Phi, int N, int spin) {
```
Comment (robertodr) [inline src/initial_guess/core.cpp]: Shouldn't this belong in `Orbital.{h,cpp}`?

Comment (stigrj) [reply src/initial_guess/core.cpp]: Yes, there is a `orbital::rotate` as well, but the current version is a bit special for the initial guess generation as it populates the output vector differently than the input. I will try to merge the two rotations and use only one.

Comment (robertodr) [reply src/initial_guess/core.cpp]: Thanks for the clarification!
